[package]
name = "raytracer"
version = "0.1.0"
authors = ["Thomas Antony <tantony@purdue.edu>"]
edition = "2018"

[dependencies]
image = "0.23.4"
rand = "0.7.3"
rayon = "1.3.0"

indicatif = {version = "*", features = ["rayon"]}
ndarray = "0.13.1"
structopt = "0.3.14"
